<?php
/*require 'Owner.php';
$O = new Owner();
$O->setName("El Mehdi Mouammine");
$O->setBirth("12-02-1996");
$O->setFrom("Khouribga-Morroco");
$O->setAdresse("282 Elqods1 Khouribga Morroco");
$O->setEmail("me.mouammine@gmail.com");
$O->setPhone("+212657075761");
$O->setDescription("I'm a computer engineer that speaks 4 languages just contact me tell me what you need and you will get it as perfect as you imagine it you can trust i'm used to freelance works just give me a try");
$l=array();
array_push($l,"English");
array_push($l,"Fluent");
$l2=array();
array_push($l2,"French");
array_push($l2,"Fluent");
$l3=array();
array_push($l3,"Arabic");
array_push($l3,"Native");
$l4=array();
array_push($l4,"Spanish");
array_push($l4,"Basic");
$O->setLanguages($l);
$O->setLanguages($l2);
$O->setLanguages($l3);
$O->setLanguages($l4);
$e=array();
array_push($e,"2013");
array_push($e,"Senior High (Math Sciences)");
$e2=array();
array_push($e2,"2013-2018");
array_push($e2,"Engineer Student at National School of Applied Sciences (Computer Engineer)");
$O->setEducations($e);
$O->setEducations($e2);
$s=array();
array_push($s,"Languages");
array_push($s,"C");
$s2=array();
array_push($s2,"Languages");
array_push($s2,"C++");
$s3=array();
array_push($s3,"Languages");
array_push($s3,"Java");
$s4=array();
array_push($s4,"Languages");
array_push($s4,"HTML");
$s5=array();
array_push($s5,"Languages");
array_push($s5,"XML");
$s6=array();
array_push($s6,"Languages");
array_push($s6,"SQL");
$s7=array();
array_push($s7,"Languages");
array_push($s7,"PLSQL");
$s8=array();
array_push($s8,"Languages");
array_push($s8,"JavaScript");
$s9=array();
array_push($s9,"Languages");
array_push($s9,"PHP");
$s10=array();
array_push($s10,"Languages");
array_push($s10,"CSS");
$O->setSkills($s);
$O->setSkills($s2);
$O->setSkills($s3);
$O->setSkills($s9);
$O->setSkills($s8);
$O->setSkills($s4);
$O->setSkills($s5);
$O->setSkills($s6);
$O->setSkills($s7);
$O->setSkills($s10);
$s11=array();
array_push($s11,"Conception");
array_push($s11,"UML");
$s12=array();
array_push($s12,"Plateforms");
array_push($s12,"JQuery");
$s13=array();
array_push($s13,"Plateforms");
array_push($s13,"AJAX");
$s14=array();
array_push($s14,"Plateforms");
array_push($s14,"JSON");
$s15=array();
array_push($s15,"Plateforms");
array_push($s15,"Bootstrap");
$s16=array();
array_push($s16,"Databases");
array_push($s16,"Oracle");
$s17=array();
array_push($s17,"Databases");
array_push($s17,"MS Access");
$s18=array();
array_push($s18,"Databases");
array_push($s18,"Mysql");
$O->setSkills($s11);
$O->setSkills($s12);
$O->setSkills($s13);
$O->setSkills($s14);
$O->setSkills($s15);
$O->setSkills($s16);
$O->setSkills($s17);
$O->setSkills($s18);
$s21=array();
array_push($s21,"Softwares");
array_push($s21,"Eclipse");
$s22=array();
array_push($s22,"Softwares");
array_push($s12,"Android Studio");
$s23=array();
array_push($s23,"Softwares");
array_push($s23,"NetBeans");
$s24=array();
array_push($s24,"Softwares");
array_push($s24,"Sublime Text + XAMP + Filezilla");
$s26=array();
array_push($s26,"Operating System");
array_push($s26,"MacOS X");
$s27=array();
array_push($s27,"Operating System");
array_push($s27,"Windows");
$s28=array();
array_push($s28,"Operating System");
array_push($s28,"Ubuntu");
$O->setSkills($s21);
$O->setSkills($s22);
$O->setSkills($s23);
$O->setSkills($s24);
$O->setSkills($s26);
$O->setSkills($s27);
$O->setSkills($s28);
$json = json_encode($O);
$fp = fopen("../Owner.json", 'w');
fwrite($fp, $json);
fclose($fp);
echo "Done";*/
?>